name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build pipez${{matrix.scalaPlatform}}${{matrix.scalaVersion}} pipezDsl${{matrix.scalaPlatform}}${{matrix.scalaVersion}}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        jvm: ['graalvm-java17:22.3.0']
        scalaVersion: ["", 3]
        scalaPlatform: ["", JS, Native]
      fail-fast: false

    env:
      SUFFIX: ${{matrix.scalaPlatform}}${{matrix.scalaVersion}}

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: ${{ matrix.jvm }}
      - name: Clean, Check code formatting, compile, test
        run: sbt clean scalafmtCheck test:scalafmtCheck pipez$SUFFIX/Test/compile pipezDsl$SUFFIX/Test/compile pipez$SUFFIX/test pipezDsl$SUFFIX/test
      - name: TOC Generator
        uses: technote-space/toc-generator@v4.0.0
